### ISSUE TITLE
PacmanLogger crashes at startup

### ISSUE THREAD

**Issue by Morganamilo** [carlocastoldi/PacmanLogger#1]
Starting PacmanLogger gets me:
```
ERROR: [4822.54] failure: `)' expected but `~' found

[2017-11-28 21:23] [ALPM] installed python-apt (1.4.0~beta3-1)
                                                     ^
```

It appears your program can not handle pkgvers with `~` in them.

**Comment by carlocastoldi** [comment]
Should have been fixed with this commit: https://github.com/carlocastoldi/PacmanLogger/commit/8ed1065e4b27741d753ece6ed1df6f70b3a6838d

Hit me up if it didn't, otherwise I'll feel free to close the issue!
Oh and thanks for reporting

**Comment by Morganamilo** [comment]
Fixed now, thanks.
